### ISSUE TITLE
As a user I can edit task details so that I can make changes to my workflow easily.

### ISSUE THREAD

**Issue by njyjn** [CS2103AUG2016-F11-C2/main#10]
`edit` functionality.

NB: I will be working on a reduced edit function which requires the user to modify each task as though they were creating a new task.

Branch: BasicEditFunction
- [x] Basic edit functionality
- [x] Tests

**Comment by njyjn** [comment]
I will be working on a reduced edit function which requires the user to modify each task as though they were creating a new task.

Branch: BasicEditFunction

**Comment by wengkiat** [comment]
Can make it closer to a real edit

**Comment by njyjn** [comment]
To follow up for v0.4.

**Comment by imhongw** [comment]
Tests complete.
