### ISSUE TITLE
As a user I can add a floating task so that I don't have to worry about a specific date to complete it.

### ISSUE THREAD

**Issue by njyjn** [CS2103AUG2016-F11-C2/main#11]
Include testing.

Extension of #4.

**Comment by njyjn** [comment]
@wengkiat to update UserGuide on regex-parser branch.

**Comment by wengkiat** [comment]
done

**Comment by njyjn** [comment]
### Up next
1. [x] Change LocalDate value for floating tasks to LocalDate.MIN
2. [x] Ensure that both LocaTime and LocalDate values for floating tasks do not get truncated. This wil enable us to differentiate these tasks from tasks due at 2359, and prevent errors truncating LocalDate.MIN.
3. [x] Ensure that these values **do not** show up in the UI, and are instead left blank.
