### ISSUE TITLE
Change update command to edit in UserGuide.

### ISSUE THREAD

**Issue by njyjn** [CS2103AUG2016-F11-C2/main#2]
~~Open to all.~~ Assigned to @wengkiat 

**Open for discussion:** Should we continue using `list` to act as a search-filter function? Project requirements do not explicitly ask for a `find` command, only functionality.

/cc @imhongw @marinirah

**Comment by wengkiat** [comment]
A search function is required, just rename list as search and we are good to go

**Comment by njyjn** [comment]
Please change to find instead.

**Comment by wengkiat** [comment]
Done, changed to find and update to edit
