### ISSUE TITLE
As a user I can Undo events i did

### ISSUE THREAD

**Issue by wengkiat** [CS2103AUG2016-F11-C2/main#30]
Undo command that is part of basic requirements
- [x] Undo functionality (Reference to PR #46)
- [x] Redo functionality.
- [x] Tests.

**Comment by njyjn** [comment]
Reference to PR #46. 

- [x] Undo functionality.
- [ ] Redo functionality.
- [ ] Tests.

**Comment by njyjn** [comment]
Tests postponed to v0.5rc.
