### ISSUE TITLE
As a user I can specify a storage location for my data file so that I can have more flexibility.

### ISSUE THREAD

**Issue by njyjn** [CS2103AUG2016-F11-C2/main#38]
1. Add a command ~~`set home '<filepath>'`~~ `storage <file/path/cmdo.xml>`.
2. @imhongw's start window to show simple instructions. (v0.4)
- [x] Implementation (f21ab679254a235ac811ee6c77506d4346139009) <br>~~\- [ ] Tests~~

**Comment by imhongw** [comment]
Tests determined to be redundant.
