### ISSUE TITLE
As a user I want to perform a fuzzy search of tasks so that I can retrieve them easily if I forget anything.

### ISSUE THREAD

**Issue by njyjn** [CS2103AUG2016-F11-C2/main#51]
Implement `find <keyword>` with a high level of fuzziness.
- [x] Basic implementation
- [x] Implement Levenshtein Distance algorithm
- [x] Tests

**Comment by njyjn** [comment]
Tests incomplete, postponed to v0.5rc.

**Comment by wengkiat** [comment]
done!
Made pull request
