### ISSUE TITLE
Bugs with edit task.

### ISSUE THREAD

**Issue by njyjn** [CS2103AUG2016-F11-C2/main#56]
The following commands give bugs:

`edit 1 'new name' 1300` on task with date and time gives 

<img width="934" alt="screen shot 2016-10-28 at 03 58 23" src="https://cloud.githubusercontent.com/assets/10694375/19782990/cd1f9702-9cc2-11e6-9df6-ba76e66d0545.png">

`edit 1 '1'` sets the task's detail to 1 but  due by 1pm.

`edit 1 'details'`only after adding a range or blocking a range makes the edited object take the range timing instead of the original timing

<img width="772" alt="screen shot 2016-10-28 at 03 59 57" src="https://cloud.githubusercontent.com/assets/10694375/19783061/039fe502-9cc3-11e6-83f5-ad4257eaccd2.png">

**Comment by wengkiat** [comment]
extract details out alr then clean the string?

**Comment by wengkiat** [comment]
the new comment is why the redo test fails

**Comment by njyjn** [comment]
First issue fixed with f6ce32a00464adb8f35f861c04304e78ff890a5d
Second issue will be fixed together with #35, waiting for @marinirah to finish.
